// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViolaTricolor.Database;

#nullable disable

namespace ViolaTricolor.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220802171404_ConnectVkAndVtUsers")]
    partial class ConnectVkAndVtUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("ViolaTricolor.Database.Entities.VkUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ViolaTricolor.Database.Entities.VTUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("vtusers", (string)null);
                });

            modelBuilder.Entity("VTUserVkUser", b =>
                {
                    b.Property<int>("VTUsersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VkUsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VTUsersId", "VkUsersId");

                    b.HasIndex("VkUsersId");

                    b.ToTable("VTUserVkUser");
                });

            modelBuilder.Entity("VTUserVkUser", b =>
                {
                    b.HasOne("ViolaTricolor.Database.Entities.VTUser", null)
                        .WithMany()
                        .HasForeignKey("VTUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViolaTricolor.Database.Entities.VkUser", null)
                        .WithMany()
                        .HasForeignKey("VkUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
